# Generated by Django 3.0.6 on 2020-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200527_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=100, unique=True),
        ),
    ]
