# Generated by Django 3.0.6 on 2020-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200527_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='money_for_loss',
            field=models.IntegerField(default=0),
        ),
    ]
