# Generated by Django 3.0.6 on 2020-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200606_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
